---
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
root: true
rules:
  import/no-unresolved: 0
  import/order:
    - error
    - newlines-between: always
env:
  browser: false
  node: true